project_id = "vmvikwamjokaalzniqwz"

[functions.n8n-callback]
verify_jwt = false

[functions.create-invoice]
verify_jwt = false

[functions.manage-coupons]
verify_jwt = false

[functions.stripe-connect-account]
verify_jwt = false

[functions.stripe-connect-status]
verify_jwt = false

[functions.generate-contract]
verify_jwt = false
